- name: setup user account with asdf tools
  include_tasks: prepare_user.yml
  tags: prepare_user
  when: powerflow2goecharger_install

- name: install things
  include_tasks: install.yml
  tags: install
  when: powerflow2goecharger_install

- name: setup config and service
  include_tasks: service.yml
  tags: service
  when: powerflow2goecharger_install

