- name: Add the group
  group:
    name: "{{powerflow2goecharger_user}}"
    system: true

- name: user
  user:
    name: "{{ powerflow2goecharger_user }}"
    group: "{{ powerflow2goecharger_user }}"
    system: yes
    shell: /bin/bash
    state: present

- name: setup asdf
  include_role:
    name: asdf
  vars:
    asdf_user: '{{ powerflow2goecharger_user }}'
